from datetime import time

# shift constants
DAY_SHIFT = 1
NIGHT_SHIFT = 2
DAY_SHIFT_START = time(7, 0, 0)
NIGHT_SHIFT_START = time(19, 0, 0)
DAY_SHIFT_START_STR = "07:00:00"
NIGHT_SHIFT_START_STR = "19:00:00"

# mach on threshold
ON_MACH_THRESHOLD = 3600

NAU_PRS_THRESHOLD = 10

PQC_FREQ_THRESHOLD = 20

NUM_MACH_IN_ZONE = 42

MES_WEIGH_THRESHOLD = 0.2